---
title: "PragMeta PRECIS-2 Scoring: Comparison Human vs ChatGPT"
author: "Tim Woelfle"
date: "2023-07-04"
output: 
  flexdashboard::flex_dashboard:
    source_code: 
    mathjax: NULL
    self_contained: TRUE
---

```{css}
table {
  margin: auto;
  border-top: 1px solid #666;
  border-bottom: 1px solid #666;
}
table thead th { border-bottom: 1px solid #ddd; }
th, td { padding: 5px; }

/* Hack to make prompt-tab scrollable again */
#chatgpt-prompt .chart-stage {
  overflow: scroll;
}
```

```{r}
library(ggplot2)
library(patchwork)

domains = c("eligibility", "recruitment", "setting", "organization", "flexibility_delivery", "flexibility_adherence", "followup", "primary_outcome", "primary_analysis")

pragmeta = read.csv2("23-06-20-random-subset.csv")
rownames(pragmeta) = pragmeta$trials.trials_id

results = read.csv("23-07-04 results.csv", row.names = 1)
results_na_3 = results
results_na_3[is.na(results_na_3)] = 3
results$sse = rowSums(abs(results_na_3[,paste0("human_score_", domains)]-results_na_3[,paste0("gpt_score_", domains)])**2)
results[,6:23] = lapply(results[,6:23], function(x) factor(x, levels=c(1,2,3,4,5,NA)))
results = results[order(results$sse),]
```

Column {data-width=60}
-------------------------------------

### Score comparisons of 30 random PragMeta publications

```{r, results="asis"}
cat("#### Sum of squared errors (SSE)\n\n")
cat("For SSE calculation only, NA is imputed as 3. SSE = sum((human-gpt)²). Examples: error of 1 in each of the 9 domains: SSE = 9×(1²)= 9; error of 4 in 1 domain: 1×(4²)=16; error of 2 in 5 domains: SSE = 5×(2²) = 20\n\n")
cat("* Mean SSE: ", round(mean(results$sse),2), " (SD ", round(sd(results$sse),2), ")\n\n", sep="")
cat("* Median SSE: ", round(median(results$sse),2), " (IQR ", round(quantile(results$sse,0.25),2), "-", round(quantile(results$sse,0.75),2), ", range ", min(results$sse), "-", max(results$sse), ")\n\n", sep="")
cat("* Modules: ", paste(names(table(pragmeta[rownames(results), "trials.module"])), table(pragmeta[rownames(results), "trials.module"]), sep=": ", collapse=", "), "\n\n", sep="")
cat("All 30 publications sorted by SSE (best at the top, worst at the bottom):\n\n")
cat("-------------------------------------\n\n")

for (ind in rownames(results)) {
  cat("#### <a href='#", ind, "' title='Jump to ChatGPT response on the right'>", pragmeta[ind, "trials.title"], "</a> (", pragmeta[ind, "trials.pub_year"], "), ", pragmeta[ind, "trials.module"], ", Sum of squared errors: ", results[ind, "sse"], "\n\n", sep="")
  
  cat(knitr::kable(data.frame(
    eligibility = c(results[ind, "human_score_eligibility"], results[ind, "gpt_score_eligibility"]),
    recruitment = c(results[ind, "human_score_recruitment"], results[ind, "gpt_score_recruitment"]),
    setting = c(results[ind, "human_score_setting"], results[ind, "gpt_score_setting"]),
    organization = c(results[ind, "human_score_organization"], results[ind, "gpt_score_organization"]),
    delivery = c(results[ind, "human_score_flexibility_delivery"], results[ind, "gpt_score_flexibility_delivery"]),
    adherence = c(results[ind, "human_score_flexibility_adherence"], results[ind, "gpt_score_flexibility_adherence"]),
    followup = c(results[ind, "human_score_followup"], results[ind, "gpt_score_followup"]),
    outcome = c(results[ind, "human_score_primary_outcome"], results[ind, "gpt_score_primary_outcome"]),
    analysis = c(results[ind, "human_score_primary_analysis"], results[ind, "gpt_score_primary_analysis"]),
    row.names = c("Human", "ChatGPT")
  ), format="html", padding=1, border=1), "\n\n")
  cat("-------------------------------------\n\n")
}
```

### Score heatmaps

```{r, fig.width=12, fig.height4}
# SSE Histogram
sse_histogram = ggplot(results) +
  geom_histogram(aes(sse), bins=15, color="black") +
  theme_bw() + xlab("Sum of squared errors")

# Heatmaps
plot_heatmap = function(data, title, limit_max) {
  ggplot(
    data, 
    aes(Human, ChatGPT)
  ) +
    geom_tile(aes(fill=Freq)) +
    geom_abline(slope=1, linewidth=0.3, color="lightgrey") +
    geom_text(aes(label=ifelse(Freq==0,"",Freq))) +
    scale_fill_gradient(low="white", high="red", limits=c(0, limit_max)) +
    ggtitle(title) +
    theme_bw() +
    theme(legend.position="none")
}

all_domains_heatmap = plot_heatmap(as.data.frame(table(Human=unlist(results[,paste0("human_score_", domains)]), ChatGPT=unlist(results[,paste0("gpt_score_", domains)]), useNA="always")), "all domains", 28)

domain_heatmaps = list()
for (i in 1:9) {
  domain_heatmaps[[i]] = plot_heatmap(as.data.frame(table(Human=results[,paste0("human_score_", domains[i])], ChatGPT=results[,paste0("gpt_score_", domains[i])], useNA="always")), domains[i], 13)
}

wrap_plots(
  wrap_plots(sse_histogram, all_domains_heatmap, nrow=2),
  wrap_plots(domain_heatmaps, ncol=3, nrow=3),
  ncol=2,
  widths=c(0.4,0.6)
)
```

Column {data-width=40 .tabset}
-------------------------------------

### ChatGPT responses per publication

```{r, results='asis'}
for (ind in rownames(results)) {
  cat("<a name='", ind, "'></a>\n\n", sep="")
  cat("#### <a href='https://doi.org/", pragmeta[ind, "trials.doi"], "' title='Open publication'>", pragmeta[ind, "trials.title"], "</a> (", pragmeta[ind, "trials.pub_year"], "), ", pragmeta[ind, "trials.module"], "\n\n", sep="")
  cat(gsub("\n", "\n\n", results[ind, "gpt_message"]), "\n\n", sep="")
}
```

### ChatGPT prompt

* Model: `gpt-3.5-turbo-16k-0613`
* Temperature: `0`

#### System prompt

```
You are an expert in clinical trial design and are tasked to assess the PRECIS-2 scores of a trial based on the full text of its publication. You have the following briefing:
---
# PRECIS-2 Domains
* Eligibility: To what extent are the participants in the trial similar to those who would receive this intervention if it was part of usual care? For example, score 5 for very pragmatic criteria essentially identical to those in usual care; score 1 for a very explanatory approach with lots of exclusions (e.g. those who don’t comply, respond to treatment, or are not at high risk for primary outcome, are children or elderly), or uses many selection tests not used in usual care.
* Recruitment: How much extra effort is made to recruit participants over and above what that would be used in the usual care setting to engage with patients? For example, score 5 for very pragmatic recruitment through usual appointments or clinic; score 1 for a very explanatory approach with targeted invitation letters, advertising in newspapers, radio plus incentives and other routes that would not be used in usual care.
* Setting: How different is the setting of the trial and the usual care setting? For example, score 5 for a very pragmatic choice using identical settings to usual care; score 1, for a very explanatory approach with only a single centre, or only specialised trial or academic centres.
* Organisation: How different are the resources, provider expertise and the organisation of care delivery in the intervention arm of the trial and those available in usual care? For example, score 5 for a very pragmatic choice that uses identical organisation to usual care; score 1 for a very explanatory approach if the trial increases staff levels, gives additional training, require more than usual experience or certification and increase resources.
* Flexibility (delivery): How different is the flexibility in how the intervention is delivered and the flexibility likely in usual care? For example, score 5 for a very pragmatic choice with identical flexibility to usual care; score 1 for a very explanatory approach if there is a strict protocol, monitoring and measures to improve compliance, with specific advice on allowed co-interventions and complications.
* Flexibility (adherence): How different is the flexibility in how participants must adhere to the intervention and the flexibility likely in usual care? For example, score 5 for a very pragmatic choice involving no more than usual encouragement to adhere to the intervention; score 1 for a very explanatory approach that involves exclusion based on adherence, and measures to improve adherence if found wanting. In some trials eg surgical trials where patients are being operated on or Intensive Care Unit trials where patients are being given IV drug therapy, this domain is not applicable as there is no compliance issue after consent has been given, so this score should be left blank.
* Follow-up: How different is the intensity of measurement and follow-up of participants in the trial and the likely follow-up in usual care? For example, score 5 for a very pragmatic approach with no more than usual follow up; score 1 for a very explanatory approach with more frequent, longer visits, unscheduled visits triggered by primary outcome event or intervening event, and more extensive data collection.
* Primary outcome: To what extent is the trial's primary outcome relevant to participants? For example, score 5 for a very pragmatic choice where the outcome is of obvious importance to participants; score 1 for a very explanatory approach using a surrogate, physiological outcome, central adjudication or use assessment expertise that is not available in usual care, or the outcome is measured at an earlier time than in usual care.
* Primary analysis: To what extent are all data included in the analysis of the primary outcome? For example, score 5 for a very pragmatic approach using intention to treat with all available data; score 1 for a very explanatory analysis that excludes ineligible post-randomisation participants, includes only completers or those following the treatment protocol.
---
```

#### User prompt

```
This is the full text to be assessed:
---
%FULLTEXT%
---

For each of the 9 domains of PRECIS-2, perform the following steps:
1. Extract 1-3 relevant quotes from the full text.
2. Explain your reasoning in 1 paragraph.
3. Give a score X from 1 (very explanatory) to 5 (very pragmatic) in square brackets like this: "Score: [X]". If the full text does not contain enough information to assess a specific domain, report "Score: [NA]".

Do not provide a final summary paragraph in the end.
```
