---
title: "Paul vs Kat. (97 publications)"
author: "Tim Woelfle"
date: 2023-08-03
output:
  html_notebook:
    code_folding: hide
    toc: yes
    toc_depth: 4
    toc_float:
      collapsed: no
      smooth_scroll: no
---

Based on: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0175213

# PRISMA

```{r, warning=F}
suppressPackageStartupMessages(library(ggplot2))

amstar = paste0("A", 1:11)
prisma = paste0("P", 1:27)

prisma_human_consensus_lmm = read.csv("results/Human Consensus_LLM_27_domains_3_options_IRR.csv")
prisma_human_consensus_human1 = read.csv("../cullis2017_amstar-prisma_human/results/Human Consensus_Human Rater 1_27_domains_3_options_IRR.csv")

amstar_human_consensus_lmm = read.csv("results/Human Consensus_LLM_11_domains_3_options_IRR.csv")
amstar_human_consensus_human1 = read.csv("../cullis2017_amstar-prisma_human/results/Human Consensus_Human Rater 1_11_domains_3_options_IRR.csv")

ggplot(data.frame(x=prisma_human_consensus_human1$cohen_kappa_w, y=prisma_human_consensus_lmm$cohen_kappa_w, text=prisma_human_consensus_lmm$X), aes(x,y)) + geom_point() + geom_text(aes(label=text), check_overlap = T, hjust="middle", vjust=-0.8) + xlim(-0.1,1) + ylim(-0.1,1) + geom_abline() + theme_bw() + xlab("Human Consensus vs Human Rater 1") + ylab("Human Consensus vs LMM") + ggtitle("PRISMA kappa")
```

```{r}
ggplot(data.frame(x=prisma_human_consensus_human1$agreement, y=prisma_human_consensus_lmm$agreement, text=prisma_human_consensus_lmm$X), aes(x,y)) + geom_point() + geom_text(aes(label=text), check_overlap = T, hjust="middle", vjust=-0.8) + xlim(-0.1,1) + ylim(-0.1,1) + geom_abline() + theme_bw() + xlab("Human Consensus vs Human Rater 1") + ylab("Human Consensus vs LMM") + ggtitle("PRISMA agreement")
```

# AMSTAR

```{r}
ggplot(data.frame(x=amstar_human_consensus_human1$cohen_kappa_w, y=amstar_human_consensus_lmm$cohen_kappa_w, text=amstar_human_consensus_lmm$X), aes(x,y)) + geom_point() + geom_text(aes(label=text), check_overlap = T, hjust="middle", vjust=-0.8) + xlim(-0.1,1) + ylim(-0.1,1) + geom_abline() + theme_bw() + xlab("Human Consensus vs Human Rater 1") + ylab("Human Consensus vs LMM") + ggtitle("AMSTAR kappa")
```

```{r}
ggplot(data.frame(x=amstar_human_consensus_human1$agreement, y=amstar_human_consensus_lmm$agreement, text=amstar_human_consensus_lmm$X), aes(x,y)) + geom_point() + geom_text(aes(label=text), check_overlap = T, hjust="middle", vjust=-0.8) + xlim(-0.1,1) + ylim(-0.1,1) + geom_abline() + theme_bw() + xlab("Human Consensus vs Human Rater 1") + ylab("Human Consensus vs LMM") + ggtitle("AMSTAR agreement")
```